# Generated by Django 3.1.4 on 2021-05-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210510_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_user',
            old_name='login',
            new_name='username',
        ),
    ]
