# Generated by Django 3.1.4 on 2021-05-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_authorization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authorization',
        ),
    ]
