# Generated by Django 3.1.4 on 2021-05-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_message',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
