# Generated by Django 3.1.4 on 2021-06-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210531_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_message',
            name='chatuser',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chat_user'),
        ),
    ]
