# Generated by Django 3.1.4 on 2021-06-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210611_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='sender',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
