# Generated by Django 3.1.4 on 2021-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210611_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to='main.chat_user')),
            ],
        ),
    ]
