# Generated by Django 3.1.4 on 2021-06-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_usersinroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersInRoom',
            new_name='in_room',
        ),
    ]
