# Generated by Django 3.1.4 on 2021-06-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210616_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_room',
            name='users',
        ),
        migrations.AddField(
            model_name='in_room',
            name='users',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chat_user'),
        ),
    ]
