# Generated by Django 3.1.4 on 2021-06-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210616_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_room',
            name='users',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
